name: crrsa
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4





dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  get_cli: ^1.8.1
  shared_preferences: ^2.3.2
  get_storage: ^2.1.1
  iconsax: ^0.0.8
  dio: ^5.7.0
  file_picker: ^9.0.0
  permission_handler: ^11.3.1
  readmore: ^2.0.0
  url_launcher: ^6.3.1
  modal_bottom_sheet: ^3.0.0
  connectivity_plus: ^4.0.0
  jwt_decoder: ^2.0.1
  #flutter_downloader: ^1.11.8
  path: ^1.9.0
  lottie: ^3.0.0
  logger: ^2.5.0
  image_picker: ^1.1.2
  device_info_plus: ^11.2.0
  pdf: ^3.11.3
  qr_flutter: ^4.1.0
  path_provider: ^2.1.5
  open_file: ^3.5.10
  #gallery_saver: ^2.3.2
  mobile_scanner: ^4.0.0

  socket_io_client: ^3.1.2
  flutter_markdown: ^0.6.18
  flutter_animate: ^4.4.1



  
  
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter



dependency_overrides:
  ffi: ^1.0.0
  intl: ^0.18.0
  collection: ^1.19.0

  
  flutter_lints: ^4.0.0





flutter:

  
  
  
  uses-material-design: true





  assets:
    - assets/logos/ccilogo.jpg
    - assets/loading.gif
    - assets/loadingtest.gif
    - assets/logos/docer-animation.gif
    - assets/logos/
    - assets/logos/mainBackground.jpg
    - assets/logos/mainlogo (1).png
    - assets/logos/Head.png
    - assets/logos/id1.jpg
    - assets/logos/IMG_2480 (1).JPG
    - assets/logos/IMG_2479 (1).JPG
    - assets/logos/10221134.jpg
    - assets/logos/2346699_315780-P8VAIG-9.jpg
    - assets/logos/Screenshot 2025-09-04 at 11.18.19 in the morning.jpg
    - assets/Searching.json




  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: NokiaPureheadline
      fonts: # Correct indentation here
        - asset: assets/fonts/Nokia Pureheadline Bold.ttf
          weight: 700
        - asset: assets/fonts/Nokia Pureheadline Light.ttf
          weight: 300



  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
